version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgresUser
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=simple_bank
      - DB_SOURCE=postgresql://postgresUser:postgres@postgres:5432/simple_bank?sslmode=disable
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d simple_bank -U postgresUser"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://postgresUser:postgres@postgres:5432/simple_bank?sslmode=disable
      - GIN_MODE=release
    depends_on:
      postgres:
        condition: service_healthy
